version: '3'
services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - examen_network
    labels:
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.rule=Host(`s120661-1.devops-ap.be`) && !PathPrefix(`/api/`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.entrypoints=websecure"

  backend:
    build:
      context: ./chatAPI
    depends_on:
      - mongodb
    networks:
      - examen_network
    labels:
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.rule=Host(`s120661-1.devops-ap.be`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend.entrypoints=websecure"

  mongodb:
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: S3cret
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - examen_network    
networks:
  examen_network:
    external: true
volumes:
  mongo-data:


